<?xml version="1.0" encoding="utf-8"?>
<Database Name="MyDbName" Class="ShippingEasyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MySource\SQLEXPRESS;Initial Catalog=MyCatalog;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CatalogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ShippingEasyShippingLabels" Member="ShippingEasyShippingLabels">
    <Type Name="ShippingEasyShippingLabel">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_number" Type="System.String" DbType="VarChar(MAX) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="refund_url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="tracking_url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="tracking_number" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ship_date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="carrier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="carrier_service" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="external_identifier" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="label_api_url" Type="System.String" DbType="varchar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>
